version: '2.1'
services:
  gogs:
    image: gogs/gogs:0.11.43
    image: gogs/gogs
    networks:
      - default
      - proxy_default

networks:
  default:
    driver: bridge
  proxy_default: 
    external: true

