version: '2.2'
services:
  nextcloud:
    networks:
      - default
      - proxy_default
    external_links:
      - proxy_nginx_1

networks:
  default:
    driver: bridge
  proxy_default: 
    external: true

