version: '2.2'
services:
  nextcloud:
    restart: always
    networks:
      - default
      - proxy_default
    external_links:
      - proxy_nginx_1

  nextcloud-db:
    restart: always

  #solr:
  #  restart: always

  redis:
    restart: always

networks:
  default:
    driver: bridge
  proxy_default: 
    external: true

