version: '2.2'
#services:

#  nginx:
#    network_mode: bridge
#    networks:
#     - default
#     - gogs_default
#     - nextcloud_default
#    external_links:
#     - nextcloud_nextcloud_1

#networks:
#  default: # this network (app2)
#    driver: bridge
#  gogs_default: # external network (app1)
#    external: true
#  nextcloud_default: # external network (app1)
#    external: true

