version: '3.6'
services:

  vault:
#    restart: always
    networks:
      - default
      - proxy_default

  consul:
#    restart: always
    networks:
      - default
      - proxy_default

#  consul-worker: 
#    restart: always

networks:
  default:
    driver: bridge
  proxy_default: 
    external: true

